name: Workflow Demo

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v4
      with:
        name: hello-artifact
        path: hello.txt
    - name: download the artifacts
      uses: actions/download-artifact@v4
      with:
        name: hello-artifact
        path: ./artifacts
    - name: display the artifacts
      run: cat ./artifacts/hello.txt